// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/common_service/system_config_service/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/common_service/system_config_service/interface.go -destination=test/mocks/service/common_service/mocks_system_config_service/mocks_system_config_service.go -package=mocks_system_config_service
//

// Package mocks_system_config_service is a generated GoMock package.
package mocks_system_config_service

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// BatchGetValueByKey mocks base method.
func (m *MockService) BatchGetValueByKey(ctx context.Context, keyList []string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetValueByKey", ctx, keyList)
	ret0, _ := ret[0].([]string)
	return ret0
}

// BatchGetValueByKey indicates an expected call of BatchGetValueByKey.
func (mr *MockServiceMockRecorder) BatchGetValueByKey(ctx, keyList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetValueByKey", reflect.TypeOf((*MockService)(nil).BatchGetValueByKey), ctx, keyList)
}

// GetValueByKey mocks base method.
func (m *MockService) GetValueByKey(ctx context.Context, name string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValueByKey", ctx, name)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetValueByKey indicates an expected call of GetValueByKey.
func (mr *MockServiceMockRecorder) GetValueByKey(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValueByKey", reflect.TypeOf((*MockService)(nil).GetValueByKey), ctx, name)
}
