// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/common_service/system_group_data_service/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/common_service/system_group_data_service/interface.go -destination=test/mocks/service/common_service/mocks_system_group_data_service/mocks_system_group_data_service.go -package=mocks_system_group_data_service
//

// Package mocks_system_group_data_service is a generated GoMock package.
package mocks_system_group_data_service

import (
	context "context"
	model "crmeb_go/internal/model"
	validation "crmeb_go/internal/validation"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetList mocks base method.
func (m *MockService) GetList(ctx context.Context, req validation.SystemGroupDataSearch) ([]*model.SystemGroupData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, req)
	ret0, _ := ret[0].([]*model.SystemGroupData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockServiceMockRecorder) GetList(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockService)(nil).GetList), ctx, req)
}

// GetListByGID mocks base method.
func (m *MockService) GetListByGID(ctx context.Context, gid int64) ([]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListByGID", ctx, gid)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListByGID indicates an expected call of GetListByGID.
func (mr *MockServiceMockRecorder) GetListByGID(ctx, gid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListByGID", reflect.TypeOf((*MockService)(nil).GetListByGID), ctx, gid)
}
