// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/system_role_repository/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/system_role_repository/interface.go -destination=test/mocks/repository/mocks_system_role_repository/mocks_system_role_repository.go -package=mocks_system_role_repository -exclude_interfaces=Reader,Writer
//

// Package mocks_system_role_repository is a generated GoMock package.
package mocks_system_role_repository

import (
	context "context"
	model "crmeb_go/internal/model"
	gen "crmeb_go/internal/repository/gen"
	validation "crmeb_go/internal/validation"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ExistRoleName mocks base method.
func (m *MockRepository) ExistRoleName(ctx context.Context, roleName string, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistRoleName", ctx, roleName, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistRoleName indicates an expected call of ExistRoleName.
func (mr *MockRepositoryMockRecorder) ExistRoleName(ctx, roleName, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistRoleName", reflect.TypeOf((*MockRepository)(nil).ExistRoleName), ctx, roleName, id)
}

// GetAllList mocks base method.
func (m *MockRepository) GetAllList(ctx context.Context) ([]*model.SystemRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllList", ctx)
	ret0, _ := ret[0].([]*model.SystemRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllList indicates an expected call of GetAllList.
func (mr *MockRepositoryMockRecorder) GetAllList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllList", reflect.TypeOf((*MockRepository)(nil).GetAllList), ctx)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, id int64) (*model.SystemRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.SystemRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, id)
}

// GetPage mocks base method.
func (m *MockRepository) GetPage(ctx context.Context, condition *validation.SystemRoleSearch) ([]*model.SystemRole, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPage", ctx, condition)
	ret0, _ := ret[0].([]*model.SystemRole)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPage indicates an expected call of GetPage.
func (mr *MockRepositoryMockRecorder) GetPage(ctx, condition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPage", reflect.TypeOf((*MockRepository)(nil).GetPage), ctx, condition)
}

// TxCreate mocks base method.
func (m *MockRepository) TxCreate(ctx context.Context, tx *gen.Query, entity *model.SystemRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxCreate", ctx, tx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// TxCreate indicates an expected call of TxCreate.
func (mr *MockRepositoryMockRecorder) TxCreate(ctx, tx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxCreate", reflect.TypeOf((*MockRepository)(nil).TxCreate), ctx, tx, entity)
}

// TxDeleteByID mocks base method.
func (m *MockRepository) TxDeleteByID(ctx context.Context, tx *gen.Query, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxDeleteByID", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TxDeleteByID indicates an expected call of TxDeleteByID.
func (mr *MockRepositoryMockRecorder) TxDeleteByID(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxDeleteByID", reflect.TypeOf((*MockRepository)(nil).TxDeleteByID), ctx, tx, id)
}

// TxUpdateByID mocks base method.
func (m *MockRepository) TxUpdateByID(ctx context.Context, tx *gen.Query, umap map[string]any, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxUpdateByID", ctx, tx, umap, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TxUpdateByID indicates an expected call of TxUpdateByID.
func (mr *MockRepositoryMockRecorder) TxUpdateByID(ctx, tx, umap, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxUpdateByID", reflect.TypeOf((*MockRepository)(nil).TxUpdateByID), ctx, tx, umap, id)
}

// UpdateByID mocks base method.
func (m *MockRepository) UpdateByID(ctx context.Context, umap map[string]any, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, umap, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockRepositoryMockRecorder) UpdateByID(ctx, umap, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockRepository)(nil).UpdateByID), ctx, umap, id)
}
