// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/system_role_repository/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/system_role_repository/interface.go -destination=test/mocks/repository/mocks_system_role_repository/mocks_system_role_repository.go -package=mocks_system_role_repository
//

// Package mocks_system_role_repository is a generated GoMock package.
package mocks_system_role_repository

import (
	context "context"
	model "crmeb_go/internal/model"
	gen "crmeb_go/internal/repository/gen"
	validation "crmeb_go/internal/validation"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// ExistRoleName mocks base method.
func (m *MockReader) ExistRoleName(ctx context.Context, roleName string, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistRoleName", ctx, roleName, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistRoleName indicates an expected call of ExistRoleName.
func (mr *MockReaderMockRecorder) ExistRoleName(ctx, roleName, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistRoleName", reflect.TypeOf((*MockReader)(nil).ExistRoleName), ctx, roleName, id)
}

// GetAllList mocks base method.
func (m *MockReader) GetAllList(ctx context.Context) ([]*model.SystemRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllList", ctx)
	ret0, _ := ret[0].([]*model.SystemRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllList indicates an expected call of GetAllList.
func (mr *MockReaderMockRecorder) GetAllList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllList", reflect.TypeOf((*MockReader)(nil).GetAllList), ctx)
}

// GetByID mocks base method.
func (m *MockReader) GetByID(ctx context.Context, id int64) (*model.SystemRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.SystemRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockReader)(nil).GetByID), ctx, id)
}

// GetPage mocks base method.
func (m *MockReader) GetPage(ctx context.Context, condition *validation.SystemRoleSearch) ([]*model.SystemRole, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPage", ctx, condition)
	ret0, _ := ret[0].([]*model.SystemRole)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPage indicates an expected call of GetPage.
func (mr *MockReaderMockRecorder) GetPage(ctx, condition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPage", reflect.TypeOf((*MockReader)(nil).GetPage), ctx, condition)
}

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
	isgomock struct{}
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// TxCreate mocks base method.
func (m *MockWriter) TxCreate(ctx context.Context, tx *gen.Query, entity *model.SystemRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxCreate", ctx, tx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// TxCreate indicates an expected call of TxCreate.
func (mr *MockWriterMockRecorder) TxCreate(ctx, tx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxCreate", reflect.TypeOf((*MockWriter)(nil).TxCreate), ctx, tx, entity)
}

// TxDeleteByID mocks base method.
func (m *MockWriter) TxDeleteByID(ctx context.Context, tx *gen.Query, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxDeleteByID", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TxDeleteByID indicates an expected call of TxDeleteByID.
func (mr *MockWriterMockRecorder) TxDeleteByID(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxDeleteByID", reflect.TypeOf((*MockWriter)(nil).TxDeleteByID), ctx, tx, id)
}

// TxUpdateByID mocks base method.
func (m *MockWriter) TxUpdateByID(ctx context.Context, tx *gen.Query, umap map[string]any, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxUpdateByID", ctx, tx, umap, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TxUpdateByID indicates an expected call of TxUpdateByID.
func (mr *MockWriterMockRecorder) TxUpdateByID(ctx, tx, umap, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxUpdateByID", reflect.TypeOf((*MockWriter)(nil).TxUpdateByID), ctx, tx, umap, id)
}

// UpdateByID mocks base method.
func (m *MockWriter) UpdateByID(ctx context.Context, umap map[string]any, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, umap, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockWriterMockRecorder) UpdateByID(ctx, umap, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockWriter)(nil).UpdateByID), ctx, umap, id)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ExistRoleName mocks base method.
func (m *MockRepository) ExistRoleName(ctx context.Context, roleName string, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistRoleName", ctx, roleName, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistRoleName indicates an expected call of ExistRoleName.
func (mr *MockRepositoryMockRecorder) ExistRoleName(ctx, roleName, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistRoleName", reflect.TypeOf((*MockRepository)(nil).ExistRoleName), ctx, roleName, id)
}

// GetAllList mocks base method.
func (m *MockRepository) GetAllList(ctx context.Context) ([]*model.SystemRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllList", ctx)
	ret0, _ := ret[0].([]*model.SystemRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllList indicates an expected call of GetAllList.
func (mr *MockRepositoryMockRecorder) GetAllList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllList", reflect.TypeOf((*MockRepository)(nil).GetAllList), ctx)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, id int64) (*model.SystemRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.SystemRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, id)
}

// GetPage mocks base method.
func (m *MockRepository) GetPage(ctx context.Context, condition *validation.SystemRoleSearch) ([]*model.SystemRole, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPage", ctx, condition)
	ret0, _ := ret[0].([]*model.SystemRole)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPage indicates an expected call of GetPage.
func (mr *MockRepositoryMockRecorder) GetPage(ctx, condition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPage", reflect.TypeOf((*MockRepository)(nil).GetPage), ctx, condition)
}

// TxCreate mocks base method.
func (m *MockRepository) TxCreate(ctx context.Context, tx *gen.Query, entity *model.SystemRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxCreate", ctx, tx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// TxCreate indicates an expected call of TxCreate.
func (mr *MockRepositoryMockRecorder) TxCreate(ctx, tx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxCreate", reflect.TypeOf((*MockRepository)(nil).TxCreate), ctx, tx, entity)
}

// TxDeleteByID mocks base method.
func (m *MockRepository) TxDeleteByID(ctx context.Context, tx *gen.Query, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxDeleteByID", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TxDeleteByID indicates an expected call of TxDeleteByID.
func (mr *MockRepositoryMockRecorder) TxDeleteByID(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxDeleteByID", reflect.TypeOf((*MockRepository)(nil).TxDeleteByID), ctx, tx, id)
}

// TxUpdateByID mocks base method.
func (m *MockRepository) TxUpdateByID(ctx context.Context, tx *gen.Query, umap map[string]any, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxUpdateByID", ctx, tx, umap, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TxUpdateByID indicates an expected call of TxUpdateByID.
func (mr *MockRepositoryMockRecorder) TxUpdateByID(ctx, tx, umap, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxUpdateByID", reflect.TypeOf((*MockRepository)(nil).TxUpdateByID), ctx, tx, umap, id)
}

// UpdateByID mocks base method.
func (m *MockRepository) UpdateByID(ctx context.Context, umap map[string]any, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, umap, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockRepositoryMockRecorder) UpdateByID(ctx, umap, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockRepository)(nil).UpdateByID), ctx, umap, id)
}
