// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"crmeb_go/internal/casbin"
	"crmeb_go/internal/handler/admin_handler/v1/admin_login_handler"
	"crmeb_go/internal/middleware"
	"crmeb_go/internal/repository"
	"crmeb_go/internal/repository/system_admin_repository"
	"crmeb_go/internal/repository/system_config_repository"
	"crmeb_go/internal/repository/system_group_data_repository"
	"crmeb_go/internal/repository/system_menu_repository"
	"crmeb_go/internal/service/admin_service/admin_login_service"
	"crmeb_go/internal/service/common_service/system_config_service"
	"crmeb_go/internal/service/common_service/system_group_data_service"
	"crmeb_go/internal/service/common_service/system_menu_service"
	"crmeb_go/pkg/cache"
	"crmeb_go/pkg/captcha"
	"crmeb_go/pkg/jwt"
	"crmeb_go/routes/admin_routes"
	"github.com/gin-gonic/gin"
	"github.com/go-redsync/redsync/v4"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

func NewWire(client redis.UniversalClient, rLock *redsync.Redsync) (*gin.Engine, func(), error) {
	recovery := middleware.NewRecoveryM()
	cors := middleware.NewCorsM()
	logM := middleware.NewLogM()
	cacheCache := cache.InitLocalCache(client)
	jwtJWT := jwt.NewJwt(cacheCache)
	authM := middleware.NewAuthM(jwtJWT)
	db, cleanup, err := repository.InitDB()
	if err != nil {
		return nil, nil, err
	}
	service, err := casbin.InitCasbinEnforcer(db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	casbinM := middleware.NewCasbinM(service)
	transaction := repository.NewTransaction(db)
	captchaCaptcha := captcha.New(cacheCache)
	system_menu_repositoryRepository := system_menu_repository.New(db)
	system_menu_serviceService := system_menu_service.New(transaction, system_menu_repositoryRepository)
	system_config_repositoryRepository := system_config_repository.New(db)
	system_config_serviceService := system_config_service.New(client, transaction, system_config_repositoryRepository)
	system_group_data_repositoryRepository := system_group_data_repository.New(db)
	system_group_data_serviceService := system_group_data_service.New(client, transaction, system_group_data_repositoryRepository)
	system_admin_repositoryRepository := system_admin_repository.New(db)
	admin_login_serviceService := admin_login_service.New(transaction, captchaCaptcha, jwtJWT, system_menu_serviceService, system_config_serviceService, system_group_data_serviceService, system_admin_repositoryRepository)
	handler := admin_login_handler.New(admin_login_serviceService)
	engine := admin_routes.NewRouter(recovery, cors, logM, authM, casbinM, handler)
	return engine, func() {
		cleanup()
	}, nil
}
