// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/system_group_data_repository/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/system_group_data_repository/interface.go -destination=test/mocks/repository/mocks_system_group_data_repository/mocks_system_group_data_repository.go -package=mocks_system_group_data_repository -exclude_interfaces=Reader,Writer
//

// Package mocks_system_group_data_repository is a generated GoMock package.
package mocks_system_group_data_repository

import (
	context "context"
	model "crmeb_go/internal/model"
	validation "crmeb_go/internal/validation"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetGroupDataPageList mocks base method.
func (m *MockRepository) GetGroupDataPageList(ctx context.Context, condition validation.SystemGroupDataSearch) ([]*model.SystemGroupData, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupDataPageList", ctx, condition)
	ret0, _ := ret[0].([]*model.SystemGroupData)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetGroupDataPageList indicates an expected call of GetGroupDataPageList.
func (mr *MockRepositoryMockRecorder) GetGroupDataPageList(ctx, condition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupDataPageList", reflect.TypeOf((*MockRepository)(nil).GetGroupDataPageList), ctx, condition)
}
