// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/common_service/system_store_staff_service/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/common_service/system_store_staff_service/interface.go -destination=test/mocks/service/common_service/mocks_system_store_staff_service/mocks_system_store_staff_service.go -package=mocks_system_store_staff_service
//

// Package mocks_system_store_staff_service is a generated GoMock package.
package mocks_system_store_staff_service

import (
	context "context"
	page "crmeb_go/internal/common/page"
	response "crmeb_go/internal/common/response"
	validation "crmeb_go/internal/validation"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetStaffList mocks base method.
func (m *MockService) GetStaffList(ctx context.Context, req *validation.GetSystemStoreStaffList) (*page.CommonPageResp[response.SystemStoreStaff], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStaffList", ctx, req)
	ret0, _ := ret[0].(*page.CommonPageResp[response.SystemStoreStaff])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStaffList indicates an expected call of GetStaffList.
func (mr *MockServiceMockRecorder) GetStaffList(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStaffList", reflect.TypeOf((*MockService)(nil).GetStaffList), ctx, req)
}
