// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/store_order_repository/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/store_order_repository/interface.go -destination=test/mocks/repository/mocks_store_order_repository/mocks_store_order_repository.go -package=mocks_store_order_repository
//

// Package mocks_store_order_repository is a generated GoMock package.
package mocks_store_order_repository

import (
	context "context"
	data "crmeb_go/internal/common/data"
	reflect "reflect"

	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// FindOrderGroupByDate mocks base method.
func (m *MockReader) FindOrderGroupByDate(ctx context.Context, start, end int64) ([]*data.StoreOrderEveryDate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrderGroupByDate", ctx, start, end)
	ret0, _ := ret[0].([]*data.StoreOrderEveryDate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrderGroupByDate indicates an expected call of FindOrderGroupByDate.
func (mr *MockReaderMockRecorder) FindOrderGroupByDate(ctx, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrderGroupByDate", reflect.TypeOf((*MockReader)(nil).FindOrderGroupByDate), ctx, start, end)
}

// FindOrderNumByDate mocks base method.
func (m *MockReader) FindOrderNumByDate(ctx context.Context, start, end int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrderNumByDate", ctx, start, end)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrderNumByDate indicates an expected call of FindOrderNumByDate.
func (mr *MockReaderMockRecorder) FindOrderNumByDate(ctx, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrderNumByDate", reflect.TypeOf((*MockReader)(nil).FindOrderNumByDate), ctx, start, end)
}

// FindPayOrderAmountByDate mocks base method.
func (m *MockReader) FindPayOrderAmountByDate(ctx context.Context, start, end int64) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPayOrderAmountByDate", ctx, start, end)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPayOrderAmountByDate indicates an expected call of FindPayOrderAmountByDate.
func (mr *MockReaderMockRecorder) FindPayOrderAmountByDate(ctx, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPayOrderAmountByDate", reflect.TypeOf((*MockReader)(nil).FindPayOrderAmountByDate), ctx, start, end)
}

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
	isgomock struct{}
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindOrderGroupByDate mocks base method.
func (m *MockRepository) FindOrderGroupByDate(ctx context.Context, start, end int64) ([]*data.StoreOrderEveryDate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrderGroupByDate", ctx, start, end)
	ret0, _ := ret[0].([]*data.StoreOrderEveryDate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrderGroupByDate indicates an expected call of FindOrderGroupByDate.
func (mr *MockRepositoryMockRecorder) FindOrderGroupByDate(ctx, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrderGroupByDate", reflect.TypeOf((*MockRepository)(nil).FindOrderGroupByDate), ctx, start, end)
}

// FindOrderNumByDate mocks base method.
func (m *MockRepository) FindOrderNumByDate(ctx context.Context, start, end int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrderNumByDate", ctx, start, end)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrderNumByDate indicates an expected call of FindOrderNumByDate.
func (mr *MockRepositoryMockRecorder) FindOrderNumByDate(ctx, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrderNumByDate", reflect.TypeOf((*MockRepository)(nil).FindOrderNumByDate), ctx, start, end)
}

// FindPayOrderAmountByDate mocks base method.
func (m *MockRepository) FindPayOrderAmountByDate(ctx context.Context, start, end int64) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPayOrderAmountByDate", ctx, start, end)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPayOrderAmountByDate indicates an expected call of FindPayOrderAmountByDate.
func (mr *MockRepositoryMockRecorder) FindPayOrderAmountByDate(ctx, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPayOrderAmountByDate", reflect.TypeOf((*MockRepository)(nil).FindPayOrderAmountByDate), ctx, start, end)
}
