// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/common_service/system_store_service/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/common_service/system_store_service/interface.go -destination=test/mocks/service/common_service/mocks_system_store_service/mocks_system_store_service.go -package=mocks_system_store_service
//

// Package mocks_system_store_service is a generated GoMock package.
package mocks_system_store_service

import (
	context "context"
	response "crmeb_go/internal/common/response"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetMapInID mocks base method.
func (m *MockService) GetMapInID(ctx context.Context, storeIDList []int64) (map[int64]response.SystemStore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMapInID", ctx, storeIDList)
	ret0, _ := ret[0].(map[int64]response.SystemStore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMapInID indicates an expected call of GetMapInID.
func (mr *MockServiceMockRecorder) GetMapInID(ctx, storeIDList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMapInID", reflect.TypeOf((*MockService)(nil).GetMapInID), ctx, storeIDList)
}
