// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/captcha/interface.go
//
// Generated by this command:
//
//	mockgen -source=pkg/captcha/interface.go -destination=test/mocks/pkg/mocks_captcha/mocks_captcha.go -package=mocks_captcha
//

// Package mocks_captcha is a generated GoMock package.
package mocks_captcha

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCaptcha is a mock of Captcha interface.
type MockCaptcha struct {
	ctrl     *gomock.Controller
	recorder *MockCaptchaMockRecorder
	isgomock struct{}
}

// MockCaptchaMockRecorder is the mock recorder for MockCaptcha.
type MockCaptchaMockRecorder struct {
	mock *MockCaptcha
}

// NewMockCaptcha creates a new mock instance.
func NewMockCaptcha(ctrl *gomock.Controller) *MockCaptcha {
	mock := &MockCaptcha{ctrl: ctrl}
	mock.recorder = &MockCaptchaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCaptcha) EXPECT() *MockCaptchaMockRecorder {
	return m.recorder
}

// Gen mocks base method.
func (m *MockCaptcha) Gen() (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gen")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Gen indicates an expected call of Gen.
func (mr *MockCaptchaMockRecorder) Gen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gen", reflect.TypeOf((*MockCaptcha)(nil).Gen))
}

// Verify mocks base method.
func (m *MockCaptcha) Verify(id, answer string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", id, answer)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockCaptchaMockRecorder) Verify(id, answer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockCaptcha)(nil).Verify), id, answer)
}
