// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameArticle = "eb_article"

// Article 文章管理表
type Article struct {
	ID            int64                 `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:文章管理ID" json:"id"`  // 文章管理ID
	Cid           string                `gorm:"column:cid;type:varchar(255);not null;comment:分类id" json:"cid"`                       // 分类id
	Title         string                `gorm:"column:title;type:varchar(255);not null;comment:文章标题" json:"title"`                   // 文章标题
	Author        string                `gorm:"column:author;type:varchar(255);comment:文章作者" json:"author"`                          // 文章作者
	ImageInput    string                `gorm:"column:image_input;type:varchar(255);not null;comment:文章图片" json:"image_input"`       // 文章图片
	Synopsis      string                `gorm:"column:synopsis;type:varchar(255);comment:文章简介" json:"synopsis"`                      // 文章简介
	ShareTitle    string                `gorm:"column:share_title;type:varchar(255);comment:文章分享标题" json:"share_title"`              // 文章分享标题
	ShareSynopsis string                `gorm:"column:share_synopsis;type:varchar(255);comment:文章分享简介" json:"share_synopsis"`        // 文章分享简介
	Visit         string                `gorm:"column:visit;type:varchar(255);comment:浏览次数" json:"visit"`                            // 浏览次数
	Sort          int64                 `gorm:"column:sort;type:int unsigned;not null;comment:排序" json:"sort"`                       // 排序
	URL           string                `gorm:"column:url;type:varchar(255);comment:原文链接" json:"url"`                                // 原文链接
	MediaID       string                `gorm:"column:media_id;type:varchar(100);comment:微信素材id" json:"media_id"`                    // 微信素材id
	Status        int64                 `gorm:"column:status;type:tinyint unsigned;not null;comment:状态" json:"status"`               // 状态
	Hide          int64                 `gorm:"column:hide;type:tinyint unsigned;not null;comment:是否隐藏" json:"hide"`                 // 是否隐藏
	AdminID       int64                 `gorm:"column:admin_id;type:int unsigned;not null;comment:管理员id" json:"admin_id"`            // 管理员id
	MerID         int64                 `gorm:"column:mer_id;type:int unsigned;comment:商户id" json:"mer_id"`                          // 商户id
	ProductID     int64                 `gorm:"column:product_id;type:int;not null;comment:商品关联id" json:"product_id"`                // 商品关联id
	IsHot         int64                 `gorm:"column:is_hot;type:tinyint unsigned;not null;comment:是否热门(小程序)" json:"is_hot"`        // 是否热门(小程序)
	IsBanner      int64                 `gorm:"column:is_banner;type:tinyint unsigned;not null;comment:是否轮播图(小程序)" json:"is_banner"` // 是否轮播图(小程序)
	Content       string                `gorm:"column:content;type:text;not null;comment:文章内容" json:"content"`                       // 文章内容
	CreatedAt     int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt     int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt     soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint" json:"-"`
}

// TableName Article's table name
func (*Article) TableName() string {
	return TableNameArticle
}
