// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameShippingTemplate = "eb_shipping_templates"

// ShippingTemplate 运费模板
type ShippingTemplate struct {
	ID        int64                 `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:编号" json:"id"`   // 编号
	Name      string                `gorm:"column:name;type:varchar(255);not null;comment:模板名称" json:"name"`         // 模板名称
	Type      bool                  `gorm:"column:type;type:tinyint(1);not null;default:1;comment:计费方式" json:"type"` // 计费方式
	Appoint   bool                  `gorm:"column:appoint;type:tinyint(1);not null;comment:指定包邮" json:"appoint"`     // 指定包邮
	Sort      int64                 `gorm:"column:sort;type:int;not null;comment:排序" json:"sort"`                    // 排序
	CreatedAt int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint" json:"-"`
}

// TableName ShippingTemplate's table name
func (*ShippingTemplate) TableName() string {
	return TableNameShippingTemplate
}
