// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameSmsRecord = "eb_sms_record"

// SmsRecord 短信发送记录表
type SmsRecord struct {
	ID         int64                 `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:短信发送记录编号" json:"id"`                         // 短信发送记录编号
	UID        string                `gorm:"column:uid;type:varchar(255);not null;comment:短信平台账号" json:"uid"`                                              // 短信平台账号
	Phone      string                `gorm:"column:phone;type:char(11);not null;comment:接受短信的手机号" json:"phone"`                                            // 接受短信的手机号
	Content    string                `gorm:"column:content;type:text;comment:短信内容" json:"content"`                                                         // 短信内容
	AddIP      string                `gorm:"column:add_ip;type:varchar(30);comment:添加记录ip" json:"add_ip"`                                                  // 添加记录ip
	Template   string                `gorm:"column:template;type:varchar(255);comment:短信模板ID" json:"template"`                                             // 短信模板ID
	Resultcode int64                 `gorm:"column:resultcode;type:int unsigned;comment:状态码 100=成功,130=失败,131=空号,132=停机,133=关机,134=无状态" json:"resultcode"` // 状态码 100=成功,130=失败,131=空号,132=停机,133=关机,134=无状态
	RecordID   int64                 `gorm:"column:record_id;type:int unsigned;comment:发送记录id" json:"record_id"`                                           // 发送记录id
	Memo       string                `gorm:"column:memo;type:text;comment:短信平台返回信息" json:"memo"`                                                           // 短信平台返回信息
	CreatedAt  int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt  int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt  soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint" json:"-"`
}

// TableName SmsRecord's table name
func (*SmsRecord) TableName() string {
	return TableNameSmsRecord
}
