// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/shopspring/decimal"
	"gorm.io/plugin/soft_delete"
)

const TableNameStorePink = "eb_store_pink"

// StorePink 拼团表
type StorePink struct {
	ID         int64                 `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:拼团ID" json:"id"`            // 拼团ID
	UID        int64                 `gorm:"column:uid;type:int unsigned;not null;comment:用户id" json:"uid"`                               // 用户id
	OrderID    string                `gorm:"column:order_id;type:varchar(32);not null;comment:订单id 生成" json:"order_id"`                   // 订单id 生成
	OrderIDKey int64                 `gorm:"column:order_id_key;type:int unsigned;not null;comment:订单id  数据库" json:"order_id_key"`        // 订单id  数据库
	TotalNum   int64                 `gorm:"column:total_num;type:int unsigned;not null;comment:购买商品个数" json:"total_num"`                 // 购买商品个数
	TotalPrice decimal.Decimal       `gorm:"column:total_price;type:decimal(10,2) unsigned;not null;comment:购买总金额" json:"total_price"`    // 购买总金额
	Cid        int64                 `gorm:"column:cid;type:int unsigned;not null;comment:拼团商品id" json:"cid"`                             // 拼团商品id
	Pid        int64                 `gorm:"column:pid;type:int unsigned;not null;comment:商品id" json:"pid"`                               // 商品id
	People     int64                 `gorm:"column:people;type:int unsigned;not null;comment:拼图总人数" json:"people"`                        // 拼图总人数
	Price      decimal.Decimal       `gorm:"column:price;type:decimal(10,2) unsigned;not null;comment:拼团商品单价" json:"price"`               // 拼团商品单价
	AddTime    int64                 `gorm:"column:add_time;type:bigint;not null;comment:开始时间" json:"add_time"`                           // 开始时间
	StopTime   int64                 `gorm:"column:stop_time;type:bigint;not null;comment:结束时间" json:"stop_time"`                         // 结束时间
	KID        int64                 `gorm:"column:k_id;type:int unsigned;not null;comment:团长id 0为团长" json:"k_id"`                        // 团长id 0为团长
	IsTpl      int64                 `gorm:"column:is_tpl;type:tinyint unsigned;not null;comment:是否发送模板消息0未发送1已发送" json:"is_tpl"`         // 是否发送模板消息0未发送1已发送
	IsRefund   int64                 `gorm:"column:is_refund;type:tinyint unsigned;not null;comment:是否退款 0未退款 1已退款" json:"is_refund"`     // 是否退款 0未退款 1已退款
	Status     int64                 `gorm:"column:status;type:tinyint unsigned;not null;default:1;comment:状态1进行中2已完成3未完成" json:"status"` // 状态1进行中2已完成3未完成
	IsVirtual  int64                 `gorm:"column:is_virtual;type:tinyint(1);not null;comment:是否虚拟拼团" json:"is_virtual"`                 // 是否虚拟拼团
	Nickname   string                `gorm:"column:nickname;type:varchar(64);not null;comment:用户昵称" json:"nickname"`                      // 用户昵称
	Avatar     string                `gorm:"column:avatar;type:varchar(256);not null;comment:用户头像" json:"avatar"`                         // 用户头像
	CreatedAt  int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt  int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt  soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint" json:"-"`
}

// TableName StorePink's table name
func (*StorePink) TableName() string {
	return TableNameStorePink
}
