// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameStoreProductRule = "eb_store_product_rule"

// StoreProductRule 商品规则值(规格)表
type StoreProductRule struct {
	ID        int64                 `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	RuleName  string                `gorm:"column:rule_name;type:varchar(32);not null;comment:规格名称" json:"rule_name"` // 规格名称
	RuleValue string                `gorm:"column:rule_value;type:text;not null;comment:规格值" json:"rule_value"`       // 规格值
	CreatedAt int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint" json:"-"`
}

// TableName StoreProductRule's table name
func (*StoreProductRule) TableName() string {
	return TableNameStoreProductRule
}
