// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameStoreProductCate = "eb_store_product_cate"

// StoreProductCate 商品分类辅助表
type StoreProductCate struct {
	ID        int64                 `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	ProductID int64                 `gorm:"column:product_id;type:int;not null;comment:商品id" json:"product_id"` // 商品id
	CateID    int64                 `gorm:"column:cate_id;type:int;not null;comment:分类id" json:"cate_id"`       // 分类id
	AddTime   int64                 `gorm:"column:add_time;type:int;not null;comment:添加时间" json:"add_time"`     // 添加时间
	CreatedAt int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint" json:"-"`
}

// TableName StoreProductCate's table name
func (*StoreProductCate) TableName() string {
	return TableNameStoreProductCate
}
