// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameStoreOrderStatus = "eb_store_order_status"

// StoreOrderStatus 订单操作记录表
type StoreOrderStatus struct {
	Oid           int64                 `gorm:"column:oid;type:int unsigned;not null;comment:订单id" json:"oid"`                       // 订单id
	ChangeType    string                `gorm:"column:change_type;type:varchar(32);not null;comment:操作类型" json:"change_type"`        // 操作类型
	ChangeMessage string                `gorm:"column:change_message;type:varchar(256);not null;comment:操作备注" json:"change_message"` // 操作备注
	CreatedAt     int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt     int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt     soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint" json:"-"`
}

// TableName StoreOrderStatus's table name
func (*StoreOrderStatus) TableName() string {
	return TableNameStoreOrderStatus
}
