// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/shopspring/decimal"
	"gorm.io/plugin/soft_delete"
)

const TableNameStoreSeckill = "eb_store_seckill"

// StoreSeckill 商品秒杀产品表
type StoreSeckill struct {
	ID           int64                 `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:商品秒杀产品表id" json:"id"`                     // 商品秒杀产品表id
	ProductID    int64                 `gorm:"column:product_id;type:int unsigned;not null;comment:商品id" json:"product_id"`                               // 商品id
	Image        string                `gorm:"column:image;type:varchar(255);not null;comment:推荐图" json:"image"`                                          // 推荐图
	Images       string                `gorm:"column:images;type:varchar(2000);not null;comment:轮播图" json:"images"`                                       // 轮播图
	Title        string                `gorm:"column:title;type:varchar(255);not null;comment:活动标题" json:"title"`                                         // 活动标题
	Info         string                `gorm:"column:info;type:varchar(255);not null;comment:简介" json:"info"`                                             // 简介
	Price        decimal.Decimal       `gorm:"column:price;type:decimal(10,2) unsigned;not null;comment:价格" json:"price"`                                 // 价格
	Cost         decimal.Decimal       `gorm:"column:cost;type:decimal(8,2) unsigned;not null;default:0.00;comment:成本" json:"cost"`                       // 成本
	OtPrice      decimal.Decimal       `gorm:"column:ot_price;type:decimal(10,2) unsigned;not null;default:0.00;comment:原价" json:"ot_price"`              // 原价
	GiveIntegral decimal.Decimal       `gorm:"column:give_integral;type:decimal(10,2) unsigned;not null;default:0.00;comment:返多少积分" json:"give_integral"` // 返多少积分
	Sort         int64                 `gorm:"column:sort;type:int unsigned;not null;comment:排序" json:"sort"`                                             // 排序
	Stock        int64                 `gorm:"column:stock;type:int unsigned;not null;comment:库存" json:"stock"`                                           // 库存
	Sales        int64                 `gorm:"column:sales;type:int unsigned;not null;comment:销量" json:"sales"`                                           // 销量
	UnitName     string                `gorm:"column:unit_name;type:varchar(16);not null;comment:单位名" json:"unit_name"`                                   // 单位名
	Postage      decimal.Decimal       `gorm:"column:postage;type:decimal(8,2) unsigned;not null;default:0.00;comment:邮费" json:"postage"`                 // 邮费
	Description  string                `gorm:"column:description;type:text;comment:内容" json:"description"`                                                // 内容
	StartTime    time.Time             `gorm:"column:start_time;type:datetime;not null;comment:开始时间" json:"start_time"`                                   // 开始时间
	StopTime     time.Time             `gorm:"column:stop_time;type:datetime;not null;comment:结束时间" json:"stop_time"`                                     // 结束时间
	Status       int64                 `gorm:"column:status;type:tinyint unsigned;not null;comment:秒杀状态 0=关闭 1=开启" json:"status"`                         // 秒杀状态 0=关闭 1=开启
	IsPostage    int64                 `gorm:"column:is_postage;type:tinyint unsigned;not null;comment:是否包邮" json:"is_postage"`                           // 是否包邮
	IsDel        int64                 `gorm:"column:is_del;type:tinyint unsigned;not null;comment:删除 0未删除1已删除" json:"is_del"`                            // 删除 0未删除1已删除
	Num          int64                 `gorm:"column:num;type:int unsigned;not null;comment:当天参与活动次数" json:"num"`                                         // 当天参与活动次数
	IsShow       int64                 `gorm:"column:is_show;type:tinyint unsigned;not null;default:1;comment:显示" json:"is_show"`                         // 显示
	TimeID       int64                 `gorm:"column:time_id;type:int;comment:时间段ID" json:"time_id"`                                                      // 时间段ID
	TempID       int64                 `gorm:"column:temp_id;type:int;not null;comment:运费模板ID" json:"temp_id"`                                            // 运费模板ID
	Weight       decimal.Decimal       `gorm:"column:weight;type:decimal(8,2);not null;default:0.00;comment:重量" json:"weight"`                            // 重量
	Volume       decimal.Decimal       `gorm:"column:volume;type:decimal(8,2);not null;default:0.00;comment:体积" json:"volume"`                            // 体积
	Quota        int64                 `gorm:"column:quota;type:int;not null;comment:限购总数,随减" json:"quota"`                                               // 限购总数,随减
	QuotaShow    int64                 `gorm:"column:quota_show;type:int;not null;comment:限购总数显示.不变" json:"quota_show"`                                   // 限购总数显示.不变
	SpecType     int64                 `gorm:"column:spec_type;type:tinyint(1);not null;comment:规格 0=单 1=多" json:"spec_type"`                             // 规格 0=单 1=多
	CreatedAt    int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt    int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt    soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint" json:"-"`
}

// TableName StoreSeckill's table name
func (*StoreSeckill) TableName() string {
	return TableNameStoreSeckill
}
