// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameSystemUserLevel = "eb_system_user_level"

// SystemUserLevel 普通会员等级
type SystemUserLevel struct {
	ID         int64                 `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Name       string                `gorm:"column:name;type:varchar(255);not null;comment:会员名称" json:"name"`               // 会员名称
	Experience int64                 `gorm:"column:experience;type:int;not null;comment:达到多少升级经验" json:"experience"`        // 达到多少升级经验
	IsShow     int64                 `gorm:"column:is_show;type:tinyint(1);not null;comment:是否显示 1=显示,0=隐藏" json:"is_show"` // 是否显示 1=显示,0=隐藏
	Grade      int64                 `gorm:"column:grade;type:int;not null;comment:会员等级" json:"grade"`                      // 会员等级
	Discount   int64                 `gorm:"column:discount;type:int;not null;default:100;comment:享受折扣" json:"discount"`    // 享受折扣
	Icon       string                `gorm:"column:icon;type:varchar(255);not null;comment:会员图标" json:"icon"`               // 会员图标
	IsDel      int64                 `gorm:"column:is_del;type:tinyint(1);not null;comment:是否删除.1=删除,0=未删除" json:"is_del"`  // 是否删除.1=删除,0=未删除
	CreatedAt  int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt  int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt  soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint" json:"-"`
}

// TableName SystemUserLevel's table name
func (*SystemUserLevel) TableName() string {
	return TableNameSystemUserLevel
}
