// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameSystemAttachment = "eb_system_attachment"

// SystemAttachment 附件管理表
type SystemAttachment struct {
	AttID     int64                 `gorm:"column:att_id;type:int;primaryKey;autoIncrement:true" json:"att_id"`
	Name      string                `gorm:"column:name;type:varchar(100);not null;comment:附件名称" json:"name"`                                                // 附件名称
	AttDir    string                `gorm:"column:att_dir;type:varchar(200);not null;comment:附件路径" json:"att_dir"`                                          // 附件路径
	SattDir   string                `gorm:"column:satt_dir;type:varchar(200);comment:压缩图片路径" json:"satt_dir"`                                               // 压缩图片路径
	AttSize   string                `gorm:"column:att_size;type:char(30);not null;comment:附件大小" json:"att_size"`                                            // 附件大小
	AttType   string                `gorm:"column:att_type;type:char(30);not null;comment:附件类型" json:"att_type"`                                            // 附件类型
	Pid       int64                 `gorm:"column:pid;type:int;not null;comment:分类ID0编辑器,1商品图片,2拼团图片,3砍价图片,4秒杀图片,5文章图片,6组合数据图， 7前台用户" json:"pid"`           // 分类ID0编辑器,1商品图片,2拼团图片,3砍价图片,4秒杀图片,5文章图片,6组合数据图， 7前台用户
	ImageType int64                 `gorm:"column:image_type;type:tinyint unsigned;not null;default:1;comment:图片上传类型 1本地 2七牛云 3OSS 4COS" json:"image_type"` // 图片上传类型 1本地 2七牛云 3OSS 4COS
	CreatedAt int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint" json:"-"`
}

// TableName SystemAttachment's table name
func (*SystemAttachment) TableName() string {
	return TableNameSystemAttachment
}
