// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameSystemGroup = "eb_system_group"

// SystemGroup 组合数据表
type SystemGroup struct {
	ID        int64                 `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:组合数据ID" json:"id"` // 组合数据ID
	Name      string                `gorm:"column:name;type:varchar(50);not null;comment:数据组名称" json:"name"`           // 数据组名称
	Info      string                `gorm:"column:info;type:varchar(256);not null;comment:简介" json:"info"`             // 简介
	FormID    int64                 `gorm:"column:form_id;type:int;not null;comment:form 表单 id" json:"form_id"`        // form 表单 id
	CreatedAt int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint" json:"-"`
}

// TableName SystemGroup's table name
func (*SystemGroup) TableName() string {
	return TableNameSystemGroup
}
