// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameSystemRole = "eb_system_role"

// SystemRole 身份管理表
type SystemRole struct {
	ID        int64                 `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:身份管理id" json:"id"` // 身份管理id
	RoleName  string                `gorm:"column:role_name;type:varchar(32);not null;comment:身份管理名称" json:"role_name"`         // 身份管理名称
	Rules     string                `gorm:"column:rules;type:text;not null;comment:身份管理权限(menus_id)" json:"rules"`              // 身份管理权限(menus_id)
	Level     int32                 `gorm:"column:level;type:tinyint unsigned;not null" json:"level"`
	Status    int32                 `gorm:"column:status;type:tinyint unsigned;not null;default:1;comment:状态" json:"status"` // 状态
	CreatedAt int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint" json:"-"`
}

// TableName SystemRole's table name
func (*SystemRole) TableName() string {
	return TableNameSystemRole
}
