// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameSystemRoleMenu = "eb_system_role_menu"

// SystemRoleMenu 角色菜单关联表
type SystemRoleMenu struct {
	Rid       int64                 `gorm:"column:rid;type:int;primaryKey;comment:角色id" json:"rid"`         // 角色id
	MenuID    int64                 `gorm:"column:menu_id;type:int;primaryKey;comment:权限id" json:"menu_id"` // 权限id
	CreatedAt int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint" json:"-"`
}

// TableName SystemRoleMenu's table name
func (*SystemRoleMenu) TableName() string {
	return TableNameSystemRoleMenu
}
