// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameSystemFormTemp = "eb_system_form_temp"

// SystemFormTemp 表单模板
type SystemFormTemp struct {
	ID        int64                 `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:表单模板id" json:"id"` // 表单模板id
	Name      string                `gorm:"column:name;type:varchar(500);not null;comment:表单名称" json:"name"`           // 表单名称
	Info      string                `gorm:"column:info;type:varchar(500);not null;comment:表单简介" json:"info"`           // 表单简介
	Content   string                `gorm:"column:content;type:text;not null;comment:表单内容" json:"content"`             // 表单内容
	CreatedAt int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint" json:"-"`
}

// TableName SystemFormTemp's table name
func (*SystemFormTemp) TableName() string {
	return TableNameSystemFormTemp
}
