// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameSystemMenu = "eb_system_menu"

// SystemMenu 系统菜单表
type SystemMenu struct {
	ID        int64                 `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Pid       int64                 `gorm:"column:pid;type:int unsigned;not null;comment:父级ID" json:"pid"`                         // 父级ID
	Name      string                `gorm:"column:name;type:varchar(100);comment:名称" json:"name"`                                  // 名称
	Icon      string                `gorm:"column:icon;type:varchar(255);comment:icon" json:"icon"`                                // icon
	Perms     string                `gorm:"column:perms;type:varchar(200);comment:权限标识" json:"perms"`                              // 权限标识
	Component string                `gorm:"column:component;type:varchar(200);comment:组件路径" json:"component"`                      // 组件路径
	MenuType  string                `gorm:"column:menu_type;type:varchar(2);default:M;comment:类型，M-目录，C-菜单，A-按钮" json:"menu_type"` // 类型，M-目录，C-菜单，A-按钮
	Sort      int64                 `gorm:"column:sort;type:int;not null;default:99999;comment:排序" json:"sort"`                    // 排序
	IsShow    int64                 `gorm:"column:is_show;type:tinyint(1);not null;default:1;comment:显示状态" json:"is_show"`         // 显示状态
	CreatedAt int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint" json:"-"`
}

// TableName SystemMenu's table name
func (*SystemMenu) TableName() string {
	return TableNameSystemMenu
}
