// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/shopspring/decimal"
	"gorm.io/plugin/soft_delete"
)

const TableNameUserExtract = "eb_user_extract"

// UserExtract 用户提现表
type UserExtract struct {
	ID           int64                 `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	UID          int64                 `gorm:"column:uid;type:int unsigned" json:"uid"`
	RealName     string                `gorm:"column:real_name;type:varchar(64);comment:名称" json:"real_name"`                                                   // 名称
	ExtractType  string                `gorm:"column:extract_type;type:varchar(32);default:bank;comment:bank = 银行卡 alipay = 支付宝 weixin=微信" json:"extract_type"` // bank = 银行卡 alipay = 支付宝 weixin=微信
	BankCode     string                `gorm:"column:bank_code;type:varchar(32);default:0;comment:银行卡" json:"bank_code"`                                        // 银行卡
	BankAddress  string                `gorm:"column:bank_address;type:varchar(256);comment:开户地址" json:"bank_address"`                                          // 开户地址
	AlipayCode   string                `gorm:"column:alipay_code;type:varchar(64);comment:支付宝账号" json:"alipay_code"`                                            // 支付宝账号
	ExtractPrice decimal.Decimal       `gorm:"column:extract_price;type:decimal(8,2) unsigned;default:0.00;comment:提现金额" json:"extract_price"`                  // 提现金额
	Mark         string                `gorm:"column:mark;type:varchar(512)" json:"mark"`
	Balance      decimal.Decimal       `gorm:"column:balance;type:decimal(8,2) unsigned;default:0.00" json:"balance"`
	FailMsg      string                `gorm:"column:fail_msg;type:varchar(128);comment:无效原因" json:"fail_msg"`        // 无效原因
	Status       int32                 `gorm:"column:status;type:tinyint;comment:-1 未通过 0 审核中 1 已提现" json:"status"`   // -1 未通过 0 审核中 1 已提现
	Wechat       string                `gorm:"column:wechat;type:varchar(15);comment:微信号" json:"wechat"`              // 微信号
	BankName     string                `gorm:"column:bank_name;type:varchar(512);comment:银行名称" json:"bank_name"`      // 银行名称
	QrcodeURL    string                `gorm:"column:qrcode_url;type:varchar(512);comment:微信收款二维码" json:"qrcode_url"` // 微信收款二维码
	CreatedAt    int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt    int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt    soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint" json:"-"`
}

// TableName UserExtract's table name
func (*UserExtract) TableName() string {
	return TableNameUserExtract
}
