// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/shopspring/decimal"
	"gorm.io/plugin/soft_delete"
)

const TableNameUserBrokerageRecord = "eb_user_brokerage_record"

// UserBrokerageRecord 用户佣金记录表
type UserBrokerageRecord struct {
	ID             int64                 `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:记录id" json:"id"`                                       // 记录id
	UID            int64                 `gorm:"column:uid;type:int;not null;comment:用户uid" json:"uid"`                                                         // 用户uid
	LinkID         string                `gorm:"column:link_id;type:varchar(32);not null;default:0;comment:关联id（orderNo,提现id）" json:"link_id"`                  // 关联id（orderNo,提现id）
	LinkType       string                `gorm:"column:link_type;type:varchar(32);not null;default:0;comment:关联类型（order,extract，yue）" json:"link_type"`         // 关联类型（order,extract，yue）
	Type           int64                 `gorm:"column:type;type:int;not null;default:1;comment:类型：1-增加，2-扣减（提现）" json:"type"`                                  // 类型：1-增加，2-扣减（提现）
	Title          string                `gorm:"column:title;type:varchar(64);not null;comment:标题" json:"title"`                                                // 标题
	Price          decimal.Decimal       `gorm:"column:price;type:decimal(8,2);not null;default:0.00;comment:金额" json:"price"`                                  // 金额
	Balance        decimal.Decimal       `gorm:"column:balance;type:decimal(16,2);not null;default:0.00;comment:剩余" json:"balance"`                             // 剩余
	Mark           string                `gorm:"column:mark;type:varchar(512);not null;comment:备注" json:"mark"`                                                 // 备注
	Status         int64                 `gorm:"column:status;type:tinyint(1);not null;default:1;comment:状态：1-订单创建，2-冻结期，3-完成，4-失效（订单退款），5-提现申请" json:"status"` // 状态：1-订单创建，2-冻结期，3-完成，4-失效（订单退款），5-提现申请
	FrozenTime     int64                 `gorm:"column:frozen_time;type:int;not null;comment:冻结期时间（天）" json:"frozen_time"`                                      // 冻结期时间（天）
	ThawTime       int64                 `gorm:"column:thaw_time;type:bigint;not null;comment:解冻时间" json:"thaw_time"`                                           // 解冻时间
	BrokerageLevel int64                 `gorm:"column:brokerage_level;type:int;comment:分销等级" json:"brokerage_level"`                                           // 分销等级
	CreatedAt      int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt      int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt      soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint" json:"-"`
}

// TableName UserBrokerageRecord's table name
func (*UserBrokerageRecord) TableName() string {
	return TableNameUserBrokerageRecord
}
