// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameUserVisitRecord = "eb_user_visit_record"

// UserVisitRecord 用户访问记录表
type UserVisitRecord struct {
	ID        int64                 `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Date      string                `gorm:"column:date;type:varchar(20);comment:日期" json:"date"`       // 日期
	UID       int64                 `gorm:"column:uid;type:int;comment:用户uid" json:"uid"`              // 用户uid
	VisitType int64                 `gorm:"column:visit_type;type:int;comment:访问类型" json:"visit_type"` // 访问类型
	CreatedAt int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint" json:"-"`
}

// TableName UserVisitRecord's table name
func (*UserVisitRecord) TableName() string {
	return TableNameUserVisitRecord
}
