// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameUserAddress = "eb_user_address"

// UserAddress 用户地址表
type UserAddress struct {
	ID        int64                 `gorm:"column:id;type:mediumint unsigned;primaryKey;autoIncrement:true;comment:用户地址id" json:"id"` // 用户地址id
	UID       int64                 `gorm:"column:uid;type:int unsigned;not null;comment:用户id" json:"uid"`                            // 用户id
	RealName  string                `gorm:"column:real_name;type:varchar(32);not null;comment:收货人姓名" json:"real_name"`                // 收货人姓名
	Phone     string                `gorm:"column:phone;type:varchar(16);not null;comment:收货人电话" json:"phone"`                        // 收货人电话
	Province  string                `gorm:"column:province;type:varchar(64);not null;comment:收货人所在省" json:"province"`                 // 收货人所在省
	City      string                `gorm:"column:city;type:varchar(64);not null;comment:收货人所在市" json:"city"`                         // 收货人所在市
	CityID    int64                 `gorm:"column:city_id;type:int;not null;comment:城市id" json:"city_id"`                             // 城市id
	District  string                `gorm:"column:district;type:varchar(64);not null;comment:收货人所在区" json:"district"`                 // 收货人所在区
	Detail    string                `gorm:"column:detail;type:varchar(256);not null;comment:收货人详细地址" json:"detail"`                   // 收货人详细地址
	PostCode  int64                 `gorm:"column:post_code;type:int;not null;comment:邮编" json:"post_code"`                           // 邮编
	Longitude string                `gorm:"column:longitude;type:varchar(16);not null;default:0;comment:经度" json:"longitude"`         // 经度
	Latitude  string                `gorm:"column:latitude;type:varchar(16);not null;default:0;comment:纬度" json:"latitude"`           // 纬度
	IsDefault int32                 `gorm:"column:is_default;type:tinyint unsigned;not null;comment:是否默认" json:"is_default"`          // 是否默认
	IsDel     int32                 `gorm:"column:is_del;type:tinyint unsigned;not null;comment:是否删除" json:"is_del"`                  // 是否删除
	CreatedAt int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint" json:"-"`
}

// TableName UserAddress's table name
func (*UserAddress) TableName() string {
	return TableNameUserAddress
}
