// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameWechatException = "eb_wechat_exceptions"

// WechatException 微信异常表
type WechatException struct {
	ID        int64                 `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:id" json:"id"` // id
	Errcode   string                `gorm:"column:errcode;type:varchar(64);comment:错误码" json:"errcode"`            // 错误码
	Errmsg    string                `gorm:"column:errmsg;type:varchar(255);comment:错误信息" json:"errmsg"`            // 错误信息
	Data      string                `gorm:"column:data;type:text;comment:回复数据" json:"data"`                        // 回复数据
	Remark    string                `gorm:"column:remark;type:text;comment:备注" json:"remark"`                      // 备注
	CreatedAt int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint" json:"-"`
}

// TableName WechatException's table name
func (*WechatException) TableName() string {
	return TableNameWechatException
}
