// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/common_service/home_service/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/common_service/home_service/interface.go -destination=test/mocks/service/common_service/mocks_home_service/mocks_home_service.go -package=mocks_home_service
//

// Package mocks_home_service is a generated GoMock package.
package mocks_home_service

import (
	context "context"
	response "crmeb_go/internal/common/response"
	reflect "reflect"

	orderedmap "github.com/iancoleman/orderedmap"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ChartOrder mocks base method.
func (m *MockService) ChartOrder(ctx context.Context) (*response.ChartOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChartOrder", ctx)
	ret0, _ := ret[0].(*response.ChartOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChartOrder indicates an expected call of ChartOrder.
func (mr *MockServiceMockRecorder) ChartOrder(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChartOrder", reflect.TypeOf((*MockService)(nil).ChartOrder), ctx)
}

// ChartOrderMonth mocks base method.
func (m *MockService) ChartOrderMonth(ctx context.Context) (*response.ChartOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChartOrderMonth", ctx)
	ret0, _ := ret[0].(*response.ChartOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChartOrderMonth indicates an expected call of ChartOrderMonth.
func (mr *MockServiceMockRecorder) ChartOrderMonth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChartOrderMonth", reflect.TypeOf((*MockService)(nil).ChartOrderMonth), ctx)
}

// ChartOrderWeek mocks base method.
func (m *MockService) ChartOrderWeek(ctx context.Context) (*response.ChartOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChartOrderWeek", ctx)
	ret0, _ := ret[0].(*response.ChartOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChartOrderWeek indicates an expected call of ChartOrderWeek.
func (mr *MockServiceMockRecorder) ChartOrderWeek(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChartOrderWeek", reflect.TypeOf((*MockService)(nil).ChartOrderWeek), ctx)
}

// ChartOrderYear mocks base method.
func (m *MockService) ChartOrderYear(ctx context.Context) (*response.ChartOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChartOrderYear", ctx)
	ret0, _ := ret[0].(*response.ChartOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChartOrderYear indicates an expected call of ChartOrderYear.
func (mr *MockServiceMockRecorder) ChartOrderYear(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChartOrderYear", reflect.TypeOf((*MockService)(nil).ChartOrderYear), ctx)
}

// ChartUser mocks base method.
func (m *MockService) ChartUser(ctx context.Context) (*orderedmap.OrderedMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChartUser", ctx)
	ret0, _ := ret[0].(*orderedmap.OrderedMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChartUser indicates an expected call of ChartUser.
func (mr *MockServiceMockRecorder) ChartUser(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChartUser", reflect.TypeOf((*MockService)(nil).ChartUser), ctx)
}

// IndexDate mocks base method.
func (m *MockService) IndexDate(ctx context.Context) (*response.HomeRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexDate", ctx)
	ret0, _ := ret[0].(*response.HomeRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IndexDate indicates an expected call of IndexDate.
func (mr *MockServiceMockRecorder) IndexDate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexDate", reflect.TypeOf((*MockService)(nil).IndexDate), ctx)
}
