// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/user_visit_record_repository/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/user_visit_record_repository/interface.go -destination=test/mocks/repository/mocks_user_visit_record_repository/mocks_user_visit_record_repository.go -package=mocks_user_visit_record_repository -exclude_interfaces=Reader,Writer
//

// Package mocks_user_visit_record_repository is a generated GoMock package.
package mocks_user_visit_record_repository

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindPageViewsByDate mocks base method.
func (m *MockRepository) FindPageViewsByDate(ctx context.Context, start, end int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPageViewsByDate", ctx, start, end)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPageViewsByDate indicates an expected call of FindPageViewsByDate.
func (mr *MockRepositoryMockRecorder) FindPageViewsByDate(ctx, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPageViewsByDate", reflect.TypeOf((*MockRepository)(nil).FindPageViewsByDate), ctx, start, end)
}
