// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/common_service/store_order_service/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/common_service/store_order_service/interface.go -destination=test/mocks/service/common_service/mocks_store_order_service/mocks_store_order_service.go -package=mocks_store_order_service
//

// Package mocks_store_order_service is a generated GoMock package.
package mocks_store_order_service

import (
	context "context"
	data "crmeb_go/internal/common/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetOrderGroupByDate mocks base method.
func (m *MockService) GetOrderGroupByDate(ctx context.Context, date string) ([]*data.StoreOrderEveryDate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderGroupByDate", ctx, date)
	ret0, _ := ret[0].([]*data.StoreOrderEveryDate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderGroupByDate indicates an expected call of GetOrderGroupByDate.
func (mr *MockServiceMockRecorder) GetOrderGroupByDate(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderGroupByDate", reflect.TypeOf((*MockService)(nil).GetOrderGroupByDate), ctx, date)
}

// GetOrderNumByDate mocks base method.
func (m *MockService) GetOrderNumByDate(ctx context.Context, params *data.DateParams) (*data.DateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderNumByDate", ctx, params)
	ret0, _ := ret[0].(*data.DateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderNumByDate indicates an expected call of GetOrderNumByDate.
func (mr *MockServiceMockRecorder) GetOrderNumByDate(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderNumByDate", reflect.TypeOf((*MockService)(nil).GetOrderNumByDate), ctx, params)
}

// GetPayOrderAmountByDate mocks base method.
func (m *MockService) GetPayOrderAmountByDate(ctx context.Context, params *data.DateParams) (*data.DateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayOrderAmountByDate", ctx, params)
	ret0, _ := ret[0].(*data.DateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayOrderAmountByDate indicates an expected call of GetPayOrderAmountByDate.
func (mr *MockServiceMockRecorder) GetPayOrderAmountByDate(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayOrderAmountByDate", reflect.TypeOf((*MockService)(nil).GetPayOrderAmountByDate), ctx, params)
}
