// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/common_service/system_role_menu_service/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/common_service/system_role_menu_service/interface.go -destination=test/mocks/service/common_service/mocks_system_role_menu_service/mocks_system_role_menu_service.go -package=mocks_system_role_menu_service
//

// Package mocks_system_role_menu_service is a generated GoMock package.
package mocks_system_role_menu_service

import (
	context "context"
	model "crmeb_go/internal/model"
	gen "crmeb_go/internal/repository/gen"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetMenuIDList mocks base method.
func (m *MockService) GetMenuIDList(ctx context.Context, roleID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenuIDList", ctx, roleID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenuIDList indicates an expected call of GetMenuIDList.
func (mr *MockServiceMockRecorder) GetMenuIDList(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenuIDList", reflect.TypeOf((*MockService)(nil).GetMenuIDList), ctx, roleID)
}

// TxBatchCreateSystemRoleMenu mocks base method.
func (m *MockService) TxBatchCreateSystemRoleMenu(ctx context.Context, tx *gen.Query, menuIDList []*model.SystemRoleMenu) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxBatchCreateSystemRoleMenu", ctx, tx, menuIDList)
	ret0, _ := ret[0].(error)
	return ret0
}

// TxBatchCreateSystemRoleMenu indicates an expected call of TxBatchCreateSystemRoleMenu.
func (mr *MockServiceMockRecorder) TxBatchCreateSystemRoleMenu(ctx, tx, menuIDList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxBatchCreateSystemRoleMenu", reflect.TypeOf((*MockService)(nil).TxBatchCreateSystemRoleMenu), ctx, tx, menuIDList)
}

// TxDeleteSystemRoleMenuByRoleID mocks base method.
func (m *MockService) TxDeleteSystemRoleMenuByRoleID(ctx context.Context, tx *gen.Query, roleID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxDeleteSystemRoleMenuByRoleID", ctx, tx, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TxDeleteSystemRoleMenuByRoleID indicates an expected call of TxDeleteSystemRoleMenuByRoleID.
func (mr *MockServiceMockRecorder) TxDeleteSystemRoleMenuByRoleID(ctx, tx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxDeleteSystemRoleMenuByRoleID", reflect.TypeOf((*MockService)(nil).TxDeleteSystemRoleMenuByRoleID), ctx, tx, roleID)
}
