// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/common_service/user_service/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/common_service/user_service/interface.go -destination=test/mocks/service/common_service/mocks_user_service/mocks_user_service.go -package=mocks_user_service
//

// Package mocks_user_service is a generated GoMock package.
package mocks_user_service

import (
	context "context"
	data "crmeb_go/internal/common/data"
	response "crmeb_go/internal/common/response"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetAddUserCountGroupDate mocks base method.
func (m *MockService) GetAddUserCountGroupDate(ctx context.Context, date string) ([]*data.UserEveryDate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddUserCountGroupDate", ctx, date)
	ret0, _ := ret[0].([]*data.UserEveryDate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddUserCountGroupDate indicates an expected call of GetAddUserCountGroupDate.
func (mr *MockServiceMockRecorder) GetAddUserCountGroupDate(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddUserCountGroupDate", reflect.TypeOf((*MockService)(nil).GetAddUserCountGroupDate), ctx, date)
}

// GetMapInID mocks base method.
func (m *MockService) GetMapInID(ctx context.Context, uidList []int64) (map[int64]response.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMapInID", ctx, uidList)
	ret0, _ := ret[0].(map[int64]response.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMapInID indicates an expected call of GetMapInID.
func (mr *MockServiceMockRecorder) GetMapInID(ctx, uidList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMapInID", reflect.TypeOf((*MockService)(nil).GetMapInID), ctx, uidList)
}

// GetRegisterNumByDate mocks base method.
func (m *MockService) GetRegisterNumByDate(ctx context.Context, params *data.DateParams) (*data.DateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegisterNumByDate", ctx, params)
	ret0, _ := ret[0].(*data.DateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegisterNumByDate indicates an expected call of GetRegisterNumByDate.
func (mr *MockServiceMockRecorder) GetRegisterNumByDate(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegisterNumByDate", reflect.TypeOf((*MockService)(nil).GetRegisterNumByDate), ctx, params)
}
