// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package admin

import (
	"crmeb_go/internal/casbin"
	"crmeb_go/internal/handler/admin_handler/v1/admin_login_handler"
	"crmeb_go/internal/middleware"
	"crmeb_go/internal/repository"
	"crmeb_go/internal/service/admin_service/admin_login_service"
	"crmeb_go/pkg/cache"
	"crmeb_go/pkg/captcha"
	"crmeb_go/pkg/jwt"
	"crmeb_go/routes/admin_routes"
	"github.com/gin-gonic/gin"
	"github.com/go-redsync/redsync/v4"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

func newWire(client redis.UniversalClient, rLock *redsync.Redsync) (*gin.Engine, func(), error) {
	recovery := middleware.NewRecoveryM()
	cors := middleware.NewCorsM()
	logM := middleware.NewLogM()
	cacheCache := cache.InitLocalCache(client)
	jwtJWT := jwt.NewJwt(cacheCache)
	authM := middleware.NewAuthM(jwtJWT)
	db, cleanup, err := repository.InitDB()
	if err != nil {
		return nil, nil, err
	}
	service, err := casbin.InitCasbinEnforcer(db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	casbinM := middleware.NewCasbinM(service)
	transaction := repository.NewTransaction(db)
	captchaCaptcha := captcha.New(cacheCache)
	admin_login_serviceService := admin_login_service.New(transaction, jwtJWT, captchaCaptcha)
	handler := admin_login_handler.New(admin_login_serviceService)
	engine := admin_routes.NewRouter(recovery, cors, logM, authM, casbinM, handler)
	return engine, func() {
		cleanup()
	}, nil
}
