// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/common_service/user_visit_record_service/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/common_service/user_visit_record_service/interface.go -destination=test/mocks/service/common_service/mocks_user_visit_record_service/mocks_user_visit_record_service.go -package=mocks_user_visit_record_service
//

// Package mocks_user_visit_record_service is a generated GoMock package.
package mocks_user_visit_record_service

import (
	context "context"
	data "crmeb_go/internal/common/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// FindPageViewsByDate mocks base method.
func (m *MockService) FindPageViewsByDate(ctx context.Context, params *data.DateParams) (*data.DateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPageViewsByDate", ctx, params)
	ret0, _ := ret[0].(*data.DateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPageViewsByDate indicates an expected call of FindPageViewsByDate.
func (mr *MockServiceMockRecorder) FindPageViewsByDate(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPageViewsByDate", reflect.TypeOf((*MockService)(nil).FindPageViewsByDate), ctx, params)
}
