// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/system_menu_repository/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/system_menu_repository/interface.go -destination=test/mocks/repository/mocks_system_menu_repository/mocks_system_menu_repository.go -package=mocks_system_menu_repository
//

// Package mocks_system_menu_repository is a generated GoMock package.
package mocks_system_menu_repository

import (
	context "context"
	model "crmeb_go/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// GetAllMenus mocks base method.
func (m *MockReader) GetAllMenus(ctx context.Context) ([]*model.SystemMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMenus", ctx)
	ret0, _ := ret[0].([]*model.SystemMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMenus indicates an expected call of GetAllMenus.
func (mr *MockReaderMockRecorder) GetAllMenus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMenus", reflect.TypeOf((*MockReader)(nil).GetAllMenus), ctx)
}

// GetAllPermissions mocks base method.
func (m *MockReader) GetAllPermissions(ctx context.Context) ([]*model.SystemMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPermissions", ctx)
	ret0, _ := ret[0].([]*model.SystemMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPermissions indicates an expected call of GetAllPermissions.
func (mr *MockReaderMockRecorder) GetAllPermissions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPermissions", reflect.TypeOf((*MockReader)(nil).GetAllPermissions), ctx)
}

// GetMenusByIDList mocks base method.
func (m *MockReader) GetMenusByIDList(ctx context.Context, menuIDList []int64) ([]*model.SystemMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenusByIDList", ctx, menuIDList)
	ret0, _ := ret[0].([]*model.SystemMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenusByIDList indicates an expected call of GetMenusByIDList.
func (mr *MockReaderMockRecorder) GetMenusByIDList(ctx, menuIDList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenusByIDList", reflect.TypeOf((*MockReader)(nil).GetMenusByIDList), ctx, menuIDList)
}

// GetMenusByUserID mocks base method.
func (m *MockReader) GetMenusByUserID(ctx context.Context, userID int64) ([]*model.SystemMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenusByUserID", ctx, userID)
	ret0, _ := ret[0].([]*model.SystemMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenusByUserID indicates an expected call of GetMenusByUserID.
func (mr *MockReaderMockRecorder) GetMenusByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenusByUserID", reflect.TypeOf((*MockReader)(nil).GetMenusByUserID), ctx, userID)
}

// GetPermissionsByUserID mocks base method.
func (m *MockReader) GetPermissionsByUserID(ctx context.Context, userID int64) ([]*model.SystemMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissionsByUserID", ctx, userID)
	ret0, _ := ret[0].([]*model.SystemMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissionsByUserID indicates an expected call of GetPermissionsByUserID.
func (mr *MockReaderMockRecorder) GetPermissionsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissionsByUserID", reflect.TypeOf((*MockReader)(nil).GetPermissionsByUserID), ctx, userID)
}

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
	isgomock struct{}
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetAllMenus mocks base method.
func (m *MockRepository) GetAllMenus(ctx context.Context) ([]*model.SystemMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMenus", ctx)
	ret0, _ := ret[0].([]*model.SystemMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMenus indicates an expected call of GetAllMenus.
func (mr *MockRepositoryMockRecorder) GetAllMenus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMenus", reflect.TypeOf((*MockRepository)(nil).GetAllMenus), ctx)
}

// GetAllPermissions mocks base method.
func (m *MockRepository) GetAllPermissions(ctx context.Context) ([]*model.SystemMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPermissions", ctx)
	ret0, _ := ret[0].([]*model.SystemMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPermissions indicates an expected call of GetAllPermissions.
func (mr *MockRepositoryMockRecorder) GetAllPermissions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPermissions", reflect.TypeOf((*MockRepository)(nil).GetAllPermissions), ctx)
}

// GetMenusByIDList mocks base method.
func (m *MockRepository) GetMenusByIDList(ctx context.Context, menuIDList []int64) ([]*model.SystemMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenusByIDList", ctx, menuIDList)
	ret0, _ := ret[0].([]*model.SystemMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenusByIDList indicates an expected call of GetMenusByIDList.
func (mr *MockRepositoryMockRecorder) GetMenusByIDList(ctx, menuIDList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenusByIDList", reflect.TypeOf((*MockRepository)(nil).GetMenusByIDList), ctx, menuIDList)
}

// GetMenusByUserID mocks base method.
func (m *MockRepository) GetMenusByUserID(ctx context.Context, userID int64) ([]*model.SystemMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenusByUserID", ctx, userID)
	ret0, _ := ret[0].([]*model.SystemMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenusByUserID indicates an expected call of GetMenusByUserID.
func (mr *MockRepositoryMockRecorder) GetMenusByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenusByUserID", reflect.TypeOf((*MockRepository)(nil).GetMenusByUserID), ctx, userID)
}

// GetPermissionsByUserID mocks base method.
func (m *MockRepository) GetPermissionsByUserID(ctx context.Context, userID int64) ([]*model.SystemMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissionsByUserID", ctx, userID)
	ret0, _ := ret[0].([]*model.SystemMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissionsByUserID indicates an expected call of GetPermissionsByUserID.
func (mr *MockRepositoryMockRecorder) GetPermissionsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissionsByUserID", reflect.TypeOf((*MockRepository)(nil).GetPermissionsByUserID), ctx, userID)
}
