// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/common_service/system_admin_service/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/common_service/system_admin_service/interface.go -destination=test/mocks/service/common_service/mocks_system_admin_service/mocks_system_admin_service.go -package=mocks_system_admin_service
//

// Package mocks_system_admin_service is a generated GoMock package.
package mocks_system_admin_service

import (
	context "context"
	page "crmeb_go/internal/common/page"
	response "crmeb_go/internal/common/response"
	validation "crmeb_go/internal/validation"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockService) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), ctx, id)
}

// Info mocks base method.
func (m *MockService) Info(ctx context.Context, id int64) (*response.SystemAdmin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Info", ctx, id)
	ret0, _ := ret[0].(*response.SystemAdmin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Info indicates an expected call of Info.
func (mr *MockServiceMockRecorder) Info(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockService)(nil).Info), ctx, id)
}

// List mocks base method.
func (m *MockService) List(ctx context.Context, req *validation.SystemAdminSearch) (*page.CommonPageResp[response.SystemAdmin], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].(*page.CommonPageResp[response.SystemAdmin])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockServiceMockRecorder) List(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockService)(nil).List), ctx, req)
}

// Save mocks base method.
func (m *MockService) Save(ctx context.Context, req *validation.SystemAdminAdd) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockServiceMockRecorder) Save(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockService)(nil).Save), ctx, req)
}

// Update mocks base method.
func (m *MockService) Update(ctx context.Context, req *validation.SystemAdminUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockServiceMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockService)(nil).Update), ctx, req)
}

// UpdateIsSms mocks base method.
func (m *MockService) UpdateIsSms(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIsSms", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIsSms indicates an expected call of UpdateIsSms.
func (mr *MockServiceMockRecorder) UpdateIsSms(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIsSms", reflect.TypeOf((*MockService)(nil).UpdateIsSms), ctx, id)
}

// UpdateStatus mocks base method.
func (m *MockService) UpdateStatus(ctx context.Context, id, status int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockServiceMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockService)(nil).UpdateStatus), ctx, id, status)
}
