// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/system_store_repository/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/system_store_repository/interface.go -destination=test/mocks/repository/mocks_system_store_repository/mocks_system_store_repository.go -package=mocks_system_store_repository -exclude_interfaces=Reader,Writer
//

// Package mocks_system_store_repository is a generated GoMock package.
package mocks_system_store_repository

import (
	context "context"
	model "crmeb_go/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetStoreList mocks base method.
func (m *MockRepository) GetStoreList(ctx context.Context, storeIDList []int64) ([]*model.SystemStore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoreList", ctx, storeIDList)
	ret0, _ := ret[0].([]*model.SystemStore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoreList indicates an expected call of GetStoreList.
func (mr *MockRepositoryMockRecorder) GetStoreList(ctx, storeIDList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoreList", reflect.TypeOf((*MockRepository)(nil).GetStoreList), ctx, storeIDList)
}
