// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/admin_service/admin_login_service/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/admin_service/admin_login_service/interface.go -destination=test/mocks/service/admin_service/mocks_admin_login_service/mocks_admin_login_service.go -package=mocks_admin_login_service
//

// Package mocks_admin_login_service is a generated GoMock package.
package mocks_admin_login_service

import (
	context "context"
	data "crmeb_go/internal/common/data"
	response "crmeb_go/internal/common/response"
	validation "crmeb_go/internal/validation"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetAdminInfo mocks base method.
func (m *MockService) GetAdminInfo(ctx context.Context, loginUserData data.LoginUser) (*response.SystemAdmin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminInfo", ctx, loginUserData)
	ret0, _ := ret[0].(*response.SystemAdmin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminInfo indicates an expected call of GetAdminInfo.
func (mr *MockServiceMockRecorder) GetAdminInfo(ctx, loginUserData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminInfo", reflect.TypeOf((*MockService)(nil).GetAdminInfo), ctx, loginUserData)
}

// GetCode mocks base method.
func (m *MockService) GetCode(ctx context.Context) (*response.ValidateCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCode", ctx)
	ret0, _ := ret[0].(*response.ValidateCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCode indicates an expected call of GetCode.
func (mr *MockServiceMockRecorder) GetCode(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCode", reflect.TypeOf((*MockService)(nil).GetCode), ctx)
}

// GetLoginPic mocks base method.
func (m *MockService) GetLoginPic(ctx context.Context) (*response.SystemLoginPic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoginPic", ctx)
	ret0, _ := ret[0].(*response.SystemLoginPic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoginPic indicates an expected call of GetLoginPic.
func (mr *MockServiceMockRecorder) GetLoginPic(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoginPic", reflect.TypeOf((*MockService)(nil).GetLoginPic), ctx)
}

// GetMenus mocks base method.
func (m *MockService) GetMenus(ctx context.Context, loginUserData data.LoginUser) ([]*response.SystemMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenus", ctx, loginUserData)
	ret0, _ := ret[0].([]*response.SystemMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenus indicates an expected call of GetMenus.
func (mr *MockServiceMockRecorder) GetMenus(ctx, loginUserData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenus", reflect.TypeOf((*MockService)(nil).GetMenus), ctx, loginUserData)
}

// SystemAdminLogin mocks base method.
func (m *MockService) SystemAdminLogin(ctx context.Context, req *validation.SystemAdminLogin, ip string) (*response.SystemLogin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SystemAdminLogin", ctx, req, ip)
	ret0, _ := ret[0].(*response.SystemLogin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SystemAdminLogin indicates an expected call of SystemAdminLogin.
func (mr *MockServiceMockRecorder) SystemAdminLogin(ctx, req, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemAdminLogin", reflect.TypeOf((*MockService)(nil).SystemAdminLogin), ctx, req, ip)
}

// SystemAdminLogout mocks base method.
func (m *MockService) SystemAdminLogout(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SystemAdminLogout", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SystemAdminLogout indicates an expected call of SystemAdminLogout.
func (mr *MockServiceMockRecorder) SystemAdminLogout(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemAdminLogout", reflect.TypeOf((*MockService)(nil).SystemAdminLogout), ctx, token)
}
