// Code generated by MockGen. DO NOT EDIT.
// Source: internal/casbin/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/casbin/interface.go -destination=test/mocks/casbin/mocks_casbin.go -package=mocks_casbin
//

// Package mocks_casbin is a generated GoMock package.
package mocks_casbin

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddPolicies mocks base method.
func (m *MockService) AddPolicies(rules []string, roleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPolicies", rules, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPolicies indicates an expected call of AddPolicies.
func (mr *MockServiceMockRecorder) AddPolicies(rules, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPolicies", reflect.TypeOf((*MockService)(nil).AddPolicies), rules, roleID)
}

// Enforce mocks base method.
func (m *MockService) Enforce(roleID, obj, act string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enforce", roleID, obj, act)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enforce indicates an expected call of Enforce.
func (mr *MockServiceMockRecorder) Enforce(roleID, obj, act any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enforce", reflect.TypeOf((*MockService)(nil).Enforce), roleID, obj, act)
}

// FreshCasbin mocks base method.
func (m *MockService) FreshCasbin() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FreshCasbin")
	ret0, _ := ret[0].(error)
	return ret0
}

// FreshCasbin indicates an expected call of FreshCasbin.
func (mr *MockServiceMockRecorder) FreshCasbin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FreshCasbin", reflect.TypeOf((*MockService)(nil).FreshCasbin))
}

// RemoveFilteredPolicy mocks base method.
func (m *MockService) RemoveFilteredPolicy(roleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFilteredPolicy", roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFilteredPolicy indicates an expected call of RemoveFilteredPolicy.
func (mr *MockServiceMockRecorder) RemoveFilteredPolicy(roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFilteredPolicy", reflect.TypeOf((*MockService)(nil).RemoveFilteredPolicy), roleID)
}

// UpdateCasbinApi mocks base method.
func (m *MockService) UpdateCasbinApi(oldPerms, newPerms string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCasbinApi", oldPerms, newPerms)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCasbinApi indicates an expected call of UpdateCasbinApi.
func (mr *MockServiceMockRecorder) UpdateCasbinApi(oldPerms, newPerms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCasbinApi", reflect.TypeOf((*MockService)(nil).UpdateCasbinApi), oldPerms, newPerms)
}
