// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/cache/interface.go
//
// Generated by this command:
//
//	mockgen -source=pkg/cache/interface.go -destination=test/mocks/pkg/mocks_cache/mocks_cache.go -package=mocks_cache
//

// Package mocks_cache is a generated GoMock package.
package mocks_cache

import (
	context "context"
	cache "crmeb_go/pkg/cache"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// DelCache mocks base method.
func (m *MockCache) DelCache(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelCache", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelCache indicates an expected call of DelCache.
func (mr *MockCacheMockRecorder) DelCache(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelCache", reflect.TypeOf((*MockCache)(nil).DelCache), key)
}

// DelLocal mocks base method.
func (m *MockCache) DelLocal(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelLocal", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelLocal indicates an expected call of DelLocal.
func (mr *MockCacheMockRecorder) DelLocal(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelLocal", reflect.TypeOf((*MockCache)(nil).DelLocal), key)
}

// GetCache mocks base method.
func (m *MockCache) GetCache(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCache", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCache indicates an expected call of GetCache.
func (mr *MockCacheMockRecorder) GetCache(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCache", reflect.TypeOf((*MockCache)(nil).GetCache), ctx, key)
}

// GetCacheOrElse mocks base method.
func (m *MockCache) GetCacheOrElse(ctx context.Context, key string, ttl time.Duration, fetcher cache.Fetcher) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCacheOrElse", ctx, key, ttl, fetcher)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCacheOrElse indicates an expected call of GetCacheOrElse.
func (mr *MockCacheMockRecorder) GetCacheOrElse(ctx, key, ttl, fetcher any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCacheOrElse", reflect.TypeOf((*MockCache)(nil).GetCacheOrElse), ctx, key, ttl, fetcher)
}

// GetCacheStatus mocks base method.
func (m *MockCache) GetCacheStatus() cache.StatusInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCacheStatus")
	ret0, _ := ret[0].(cache.StatusInfo)
	return ret0
}

// GetCacheStatus indicates an expected call of GetCacheStatus.
func (mr *MockCacheMockRecorder) GetCacheStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCacheStatus", reflect.TypeOf((*MockCache)(nil).GetCacheStatus))
}

// GetKeyStatus mocks base method.
func (m *MockCache) GetKeyStatus(key string) cache.KeyInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyStatus", key)
	ret0, _ := ret[0].(cache.KeyInfo)
	return ret0
}

// GetKeyStatus indicates an expected call of GetKeyStatus.
func (mr *MockCacheMockRecorder) GetKeyStatus(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyStatus", reflect.TypeOf((*MockCache)(nil).GetKeyStatus), key)
}

// GetLocal mocks base method.
func (m *MockCache) GetLocal(key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocal", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocal indicates an expected call of GetLocal.
func (mr *MockCacheMockRecorder) GetLocal(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocal", reflect.TypeOf((*MockCache)(nil).GetLocal), key)
}

// SetCache mocks base method.
func (m *MockCache) SetCache(ctx context.Context, key, value string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCache", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCache indicates an expected call of SetCache.
func (mr *MockCacheMockRecorder) SetCache(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCache", reflect.TypeOf((*MockCache)(nil).SetCache), ctx, key, value, ttl)
}

// SetLocal mocks base method.
func (m *MockCache) SetLocal(key, value string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLocal", key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLocal indicates an expected call of SetLocal.
func (mr *MockCacheMockRecorder) SetLocal(key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLocal", reflect.TypeOf((*MockCache)(nil).SetLocal), key, value, ttl)
}

// MockFetcher is a mock of Fetcher interface.
type MockFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockFetcherMockRecorder
	isgomock struct{}
}

// MockFetcherMockRecorder is the mock recorder for MockFetcher.
type MockFetcherMockRecorder struct {
	mock *MockFetcher
}

// NewMockFetcher creates a new mock instance.
func NewMockFetcher(ctrl *gomock.Controller) *MockFetcher {
	mock := &MockFetcher{ctrl: ctrl}
	mock.recorder = &MockFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFetcher) EXPECT() *MockFetcherMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockFetcher) Fetch(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockFetcherMockRecorder) Fetch(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockFetcher)(nil).Fetch), ctx, key)
}
