// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/oss/interface.go
//
// Generated by this command:
//
//	mockgen -source=pkg/oss/interface.go -destination=test/mocks/pkg/mocks_oss/mocks_oss.go -package=mocks_oss
//

// Package mocks_oss is a generated GoMock package.
package mocks_oss

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// BatchDelete mocks base method.
func (m *MockClient) BatchDelete(srcPath []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", srcPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockClientMockRecorder) BatchDelete(srcPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockClient)(nil).BatchDelete), srcPath)
}

// Copy mocks base method.
func (m *MockClient) Copy(srcPath, destPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", srcPath, destPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Copy indicates an expected call of Copy.
func (mr *MockClientMockRecorder) Copy(srcPath, destPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockClient)(nil).Copy), srcPath, destPath)
}

// Delete mocks base method.
func (m *MockClient) Delete(srcPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", srcPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClientMockRecorder) Delete(srcPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClient)(nil).Delete), srcPath)
}

// Download mocks base method.
func (m *MockClient) Download(objectKey, downloadPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", objectKey, downloadPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Download indicates an expected call of Download.
func (mr *MockClientMockRecorder) Download(objectKey, downloadPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockClient)(nil).Download), objectKey, downloadPath)
}

// GetFileSize mocks base method.
func (m *MockClient) GetFileSize(filePath string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileSize", filePath)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileSize indicates an expected call of GetFileSize.
func (mr *MockClientMockRecorder) GetFileSize(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileSize", reflect.TypeOf((*MockClient)(nil).GetFileSize), filePath)
}

// GetOnly mocks base method.
func (m *MockClient) GetOnly(path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOnly", path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOnly indicates an expected call of GetOnly.
func (mr *MockClientMockRecorder) GetOnly(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOnly", reflect.TypeOf((*MockClient)(nil).GetOnly), path)
}

// IsExist mocks base method.
func (m *MockClient) IsExist(filePath string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExist", filePath)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsExist indicates an expected call of IsExist.
func (mr *MockClientMockRecorder) IsExist(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExist", reflect.TypeOf((*MockClient)(nil).IsExist), filePath)
}

// Rename mocks base method.
func (m *MockClient) Rename(srcPath, destPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", srcPath, destPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockClientMockRecorder) Rename(srcPath, destPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockClient)(nil).Rename), srcPath, destPath)
}

// SignURL mocks base method.
func (m *MockClient) SignURL(ossFilePath, fileName string, expiresInSec int64, category int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignURL", ossFilePath, fileName, expiresInSec, category)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignURL indicates an expected call of SignURL.
func (mr *MockClientMockRecorder) SignURL(ossFilePath, fileName, expiresInSec, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignURL", reflect.TypeOf((*MockClient)(nil).SignURL), ossFilePath, fileName, expiresInSec, category)
}

// UploadFile mocks base method.
func (m *MockClient) UploadFile(objectName, filePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", objectName, filePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockClientMockRecorder) UploadFile(objectName, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockClient)(nil).UploadFile), objectName, filePath)
}
