// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/system_role_menu_repository/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/system_role_menu_repository/interface.go -destination=test/mocks/repository/mocks_system_role_menu_repository/mocks_system_role_menu_repository.go -package=mocks_system_role_menu_repository -exclude_interfaces=Reader,Writer
//

// Package mocks_system_role_menu_repository is a generated GoMock package.
package mocks_system_role_menu_repository

import (
	context "context"
	model "crmeb_go/internal/model"
	gen "crmeb_go/internal/repository/gen"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetMenuIDListByRoleID mocks base method.
func (m *MockRepository) GetMenuIDListByRoleID(ctx context.Context, roleID int64) ([]*model.SystemRoleMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenuIDListByRoleID", ctx, roleID)
	ret0, _ := ret[0].([]*model.SystemRoleMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenuIDListByRoleID indicates an expected call of GetMenuIDListByRoleID.
func (mr *MockRepositoryMockRecorder) GetMenuIDListByRoleID(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenuIDListByRoleID", reflect.TypeOf((*MockRepository)(nil).GetMenuIDListByRoleID), ctx, roleID)
}

// TxBatchCreate mocks base method.
func (m *MockRepository) TxBatchCreate(ctx context.Context, tx *gen.Query, entityList []*model.SystemRoleMenu) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxBatchCreate", ctx, tx, entityList)
	ret0, _ := ret[0].(error)
	return ret0
}

// TxBatchCreate indicates an expected call of TxBatchCreate.
func (mr *MockRepositoryMockRecorder) TxBatchCreate(ctx, tx, entityList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxBatchCreate", reflect.TypeOf((*MockRepository)(nil).TxBatchCreate), ctx, tx, entityList)
}

// TxDeleteByRoleID mocks base method.
func (m *MockRepository) TxDeleteByRoleID(ctx context.Context, tx *gen.Query, roleID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxDeleteByRoleID", ctx, tx, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TxDeleteByRoleID indicates an expected call of TxDeleteByRoleID.
func (mr *MockRepositoryMockRecorder) TxDeleteByRoleID(ctx, tx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxDeleteByRoleID", reflect.TypeOf((*MockRepository)(nil).TxDeleteByRoleID), ctx, tx, roleID)
}
