// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/system_config_repository/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/system_config_repository/interface.go -destination=test/mocks/repository/mocks_system_config_repository/mocks_system_config_repository.go -package=mocks_system_config_repository
//

// Package mocks_system_config_repository is a generated GoMock package.
package mocks_system_config_repository

import (
	context "context"
	model "crmeb_go/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// GetConfigALL mocks base method.
func (m *MockReader) GetConfigALL(ctx context.Context) ([]*model.SystemConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigALL", ctx)
	ret0, _ := ret[0].([]*model.SystemConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigALL indicates an expected call of GetConfigALL.
func (mr *MockReaderMockRecorder) GetConfigALL(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigALL", reflect.TypeOf((*MockReader)(nil).GetConfigALL), ctx)
}

// GetConfigByName mocks base method.
func (m *MockReader) GetConfigByName(ctx context.Context, name string) (*model.SystemConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigByName", ctx, name)
	ret0, _ := ret[0].(*model.SystemConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigByName indicates an expected call of GetConfigByName.
func (mr *MockReaderMockRecorder) GetConfigByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigByName", reflect.TypeOf((*MockReader)(nil).GetConfigByName), ctx, name)
}

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
	isgomock struct{}
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetConfigALL mocks base method.
func (m *MockRepository) GetConfigALL(ctx context.Context) ([]*model.SystemConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigALL", ctx)
	ret0, _ := ret[0].([]*model.SystemConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigALL indicates an expected call of GetConfigALL.
func (mr *MockRepositoryMockRecorder) GetConfigALL(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigALL", reflect.TypeOf((*MockRepository)(nil).GetConfigALL), ctx)
}

// GetConfigByName mocks base method.
func (m *MockRepository) GetConfigByName(ctx context.Context, name string) (*model.SystemConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigByName", ctx, name)
	ret0, _ := ret[0].(*model.SystemConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigByName indicates an expected call of GetConfigByName.
func (mr *MockRepositoryMockRecorder) GetConfigByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigByName", reflect.TypeOf((*MockRepository)(nil).GetConfigByName), ctx, name)
}
