// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/system_admin_repository/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/system_admin_repository/interface.go -destination=test/mocks/repository/mocks_system_admin_repository/mocks_system_admin_repository.go -package=mocks_system_admin_repository -exclude_interfaces=Reader,Writer
//

// Package mocks_system_admin_repository is a generated GoMock package.
package mocks_system_admin_repository

import (
	context "context"
	model "crmeb_go/internal/model"
	validation "crmeb_go/internal/validation"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, entity *model.SystemAdmin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, entity)
}

// DeleteByID mocks base method.
func (m *MockRepository) DeleteByID(ctx context.Context, ID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockRepositoryMockRecorder) DeleteByID(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockRepository)(nil).DeleteByID), ctx, ID)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, id int64) (*model.SystemAdmin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.SystemAdmin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, id)
}

// GetPage mocks base method.
func (m *MockRepository) GetPage(ctx context.Context, condition *validation.SystemAdminSearch) ([]*model.SystemAdmin, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPage", ctx, condition)
	ret0, _ := ret[0].([]*model.SystemAdmin)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPage indicates an expected call of GetPage.
func (mr *MockRepositoryMockRecorder) GetPage(ctx, condition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPage", reflect.TypeOf((*MockRepository)(nil).GetPage), ctx, condition)
}

// GetUser mocks base method.
func (m *MockRepository) GetUser(ctx context.Context, userName string) (*model.SystemAdmin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userName)
	ret0, _ := ret[0].(*model.SystemAdmin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockRepositoryMockRecorder) GetUser(ctx, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockRepository)(nil).GetUser), ctx, userName)
}

// IsExistAccount mocks base method.
func (m *MockRepository) IsExistAccount(ctx context.Context, account string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExistAccount", ctx, account)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsExistAccount indicates an expected call of IsExistAccount.
func (mr *MockRepositoryMockRecorder) IsExistAccount(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExistAccount", reflect.TypeOf((*MockRepository)(nil).IsExistAccount), ctx, account)
}

// IsSingleAccount mocks base method.
func (m *MockRepository) IsSingleAccount(ctx context.Context, id int64, account string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSingleAccount", ctx, id, account)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSingleAccount indicates an expected call of IsSingleAccount.
func (mr *MockRepositoryMockRecorder) IsSingleAccount(ctx, id, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSingleAccount", reflect.TypeOf((*MockRepository)(nil).IsSingleAccount), ctx, id, account)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, entity *model.SystemAdmin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, entity)
}

// UpdateFields mocks base method.
func (m *MockRepository) UpdateFields(ctx context.Context, ID int64, umap map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFields", ctx, ID, umap)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFields indicates an expected call of UpdateFields.
func (mr *MockRepositoryMockRecorder) UpdateFields(ctx, ID, umap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFields", reflect.TypeOf((*MockRepository)(nil).UpdateFields), ctx, ID, umap)
}
