// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/user_repository/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/user_repository/interface.go -destination=test/mocks/repository/mocks_user_repository/mocks_user_repository.go -package=mocks_user_repository
//

// Package mocks_user_repository is a generated GoMock package.
package mocks_user_repository

import (
	context "context"
	data "crmeb_go/internal/common/data"
	model "crmeb_go/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// GetAddUserCountGroupDate mocks base method.
func (m *MockReader) GetAddUserCountGroupDate(ctx context.Context, start, end int64) ([]*data.UserEveryDate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddUserCountGroupDate", ctx, start, end)
	ret0, _ := ret[0].([]*data.UserEveryDate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddUserCountGroupDate indicates an expected call of GetAddUserCountGroupDate.
func (mr *MockReaderMockRecorder) GetAddUserCountGroupDate(ctx, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddUserCountGroupDate", reflect.TypeOf((*MockReader)(nil).GetAddUserCountGroupDate), ctx, start, end)
}

// GetRegisterNumByDate mocks base method.
func (m *MockReader) GetRegisterNumByDate(ctx context.Context, start, end int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegisterNumByDate", ctx, start, end)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegisterNumByDate indicates an expected call of GetRegisterNumByDate.
func (mr *MockReaderMockRecorder) GetRegisterNumByDate(ctx, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegisterNumByDate", reflect.TypeOf((*MockReader)(nil).GetRegisterNumByDate), ctx, start, end)
}

// GetUserListInID mocks base method.
func (m *MockReader) GetUserListInID(ctx context.Context, idList []int64) ([]*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserListInID", ctx, idList)
	ret0, _ := ret[0].([]*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserListInID indicates an expected call of GetUserListInID.
func (mr *MockReaderMockRecorder) GetUserListInID(ctx, idList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserListInID", reflect.TypeOf((*MockReader)(nil).GetUserListInID), ctx, idList)
}

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
	isgomock struct{}
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetAddUserCountGroupDate mocks base method.
func (m *MockRepository) GetAddUserCountGroupDate(ctx context.Context, start, end int64) ([]*data.UserEveryDate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddUserCountGroupDate", ctx, start, end)
	ret0, _ := ret[0].([]*data.UserEveryDate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddUserCountGroupDate indicates an expected call of GetAddUserCountGroupDate.
func (mr *MockRepositoryMockRecorder) GetAddUserCountGroupDate(ctx, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddUserCountGroupDate", reflect.TypeOf((*MockRepository)(nil).GetAddUserCountGroupDate), ctx, start, end)
}

// GetRegisterNumByDate mocks base method.
func (m *MockRepository) GetRegisterNumByDate(ctx context.Context, start, end int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegisterNumByDate", ctx, start, end)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegisterNumByDate indicates an expected call of GetRegisterNumByDate.
func (mr *MockRepositoryMockRecorder) GetRegisterNumByDate(ctx, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegisterNumByDate", reflect.TypeOf((*MockRepository)(nil).GetRegisterNumByDate), ctx, start, end)
}

// GetUserListInID mocks base method.
func (m *MockRepository) GetUserListInID(ctx context.Context, idList []int64) ([]*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserListInID", ctx, idList)
	ret0, _ := ret[0].([]*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserListInID indicates an expected call of GetUserListInID.
func (mr *MockRepositoryMockRecorder) GetUserListInID(ctx, idList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserListInID", reflect.TypeOf((*MockRepository)(nil).GetUserListInID), ctx, idList)
}
