// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/common_service/system_menu_service/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/common_service/system_menu_service/interface.go -destination=test/mocks/service/common_service/mocks_system_menu_service/mocks_system_menu_service.go -package=mocks_system_menu_service
//

// Package mocks_system_menu_service is a generated GoMock package.
package mocks_system_menu_service

import (
	context "context"
	response "crmeb_go/internal/common/response"
	model "crmeb_go/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// BuildTree mocks base method.
func (m *MockService) BuildTree(menuList []*response.MenuCheck) []*response.MenuCheck {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildTree", menuList)
	ret0, _ := ret[0].([]*response.MenuCheck)
	return ret0
}

// BuildTree indicates an expected call of BuildTree.
func (mr *MockServiceMockRecorder) BuildTree(menuList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildTree", reflect.TypeOf((*MockService)(nil).BuildTree), menuList)
}

// GetAllMenus mocks base method.
func (m *MockService) GetAllMenus(ctx context.Context) ([]*model.SystemMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMenus", ctx)
	ret0, _ := ret[0].([]*model.SystemMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMenus indicates an expected call of GetAllMenus.
func (mr *MockServiceMockRecorder) GetAllMenus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMenus", reflect.TypeOf((*MockService)(nil).GetAllMenus), ctx)
}

// GetAllPermissions mocks base method.
func (m *MockService) GetAllPermissions(ctx context.Context) ([]*model.SystemMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPermissions", ctx)
	ret0, _ := ret[0].([]*model.SystemMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPermissions indicates an expected call of GetAllPermissions.
func (mr *MockServiceMockRecorder) GetAllPermissions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPermissions", reflect.TypeOf((*MockService)(nil).GetAllPermissions), ctx)
}

// GetCacheList mocks base method.
func (m *MockService) GetCacheList(ctx context.Context) ([]*model.SystemMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCacheList", ctx)
	ret0, _ := ret[0].([]*model.SystemMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCacheList indicates an expected call of GetCacheList.
func (mr *MockServiceMockRecorder) GetCacheList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCacheList", reflect.TypeOf((*MockService)(nil).GetCacheList), ctx)
}

// GetCacheTree mocks base method.
func (m *MockService) GetCacheTree(ctx context.Context) ([]*response.MenuCheck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCacheTree", ctx)
	ret0, _ := ret[0].([]*response.MenuCheck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCacheTree indicates an expected call of GetCacheTree.
func (mr *MockServiceMockRecorder) GetCacheTree(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCacheTree", reflect.TypeOf((*MockService)(nil).GetCacheTree), ctx)
}

// GetMenusByIDList mocks base method.
func (m *MockService) GetMenusByIDList(ctx context.Context, menuIDList []int64) ([]*model.SystemMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenusByIDList", ctx, menuIDList)
	ret0, _ := ret[0].([]*model.SystemMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenusByIDList indicates an expected call of GetMenusByIDList.
func (mr *MockServiceMockRecorder) GetMenusByIDList(ctx, menuIDList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenusByIDList", reflect.TypeOf((*MockService)(nil).GetMenusByIDList), ctx, menuIDList)
}

// GetUserMenus mocks base method.
func (m *MockService) GetUserMenus(ctx context.Context, userID int64) ([]*model.SystemMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserMenus", ctx, userID)
	ret0, _ := ret[0].([]*model.SystemMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserMenus indicates an expected call of GetUserMenus.
func (mr *MockServiceMockRecorder) GetUserMenus(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserMenus", reflect.TypeOf((*MockService)(nil).GetUserMenus), ctx, userID)
}

// GetUserPermissions mocks base method.
func (m *MockService) GetUserPermissions(ctx context.Context, userID int64) ([]*model.SystemMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPermissions", ctx, userID)
	ret0, _ := ret[0].([]*model.SystemMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPermissions indicates an expected call of GetUserPermissions.
func (mr *MockServiceMockRecorder) GetUserPermissions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPermissions", reflect.TypeOf((*MockService)(nil).GetUserPermissions), ctx, userID)
}
